add validations on extension and size

diff --git a/.github/workflows/release-nightlies.yaml b/.github/workflows/release-nightlies.yaml
--- a/.github/workflows/release-nightlies.yaml
+++ b/.github/workflows/release-nightlies.yaml
@@ -153,6 +153,29 @@ jobs:
             ARTIFACT_NAME=ros2-rolling-nightly-$OS-$ARCH.$EXT
             echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
             curl -u "$GH_USER:$GH_TOKEN" --retry 3 --retry-delay 5 --silent --globoff  "${MATRIX_TARGET_URL}" -o "$ARTIFACT_NAME"
+            # Check if file is empty
+            if [ ! -s "$ARTIFACT_NAME" ]; then
+                echo "ERROR: Downloaded file $ARTIFACT_NAME is empty!"
+                exit 1
+            fi
+
+            # Check if compression matches the extension
+            FILE_TYPE=$(file -b "$ARTIFACT_NAME")
+
+            case "$EXT" in
+                zip)
+                    [[ "$FILE_TYPE" == *"Zip archive data"* ]] || { echo "Format mismatch: Expected Zip"; exit 1; }
+                    ;;
+                tar.bz2)
+                    [[ "$FILE_TYPE" == *"bzip2 compressed data"* ]] || { echo "Format mismatch: Expected Bzip2"; exit 1; }
+                    ;;
+                *)
+                    echo "Warning: No specific validation for extension .$EXT."
+                    exit 1
+                    ;;
+            esac
+
+            echo "Validation successful: $ARTIFACT_NAME is not empty and matches $EXT format."
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           GH_USER: ${{secrets.GH_USER}}
